/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Benhnhan.View;


/**
 *
 * @author VanQuyen
 */

import java.awt.event.ActionListener;
import java.util.Date;
import javax.swing.JOptionPane;
import Benhnhan.Dao.BenhnhanDao;
import Benhnhan.entity.Benhnhan;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;

public class AddBenhnhanJFrame extends javax.swing.JFrame {
    
    BenhnhanDao benhnhandao;
    /**
     * Creates new form AddJFrame
     */
    public AddBenhnhanJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        addnam = new javax.swing.JCheckBox();
        addnu = new javax.swing.JCheckBox();
        hovaten = new javax.swing.JTextField();
        sodienthoai = new javax.swing.JTextField();
        quequan = new javax.swing.JTextField();
        hktt = new javax.swing.JTextField();
        chonanh = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        anh = new javax.swing.JLabel();
        ngaysinh = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        mabenhnhan = new javax.swing.JTextField();
        mabhyt = new javax.swing.JTextField();
        bacsikham = new javax.swing.JTextField();
        trieuchung = new javax.swing.JTextField();
        chandoan = new javax.swing.JTextField();
        ketluan = new javax.swing.JTextField();
        chidinh = new javax.swing.JTextField();
        tinhtrangnhapvien = new javax.swing.JComboBox<>();
        ngaynhapvien = new com.toedter.calendar.JDateChooser();
        ngayxuatvien = new com.toedter.calendar.JDateChooser();
        buttonhuybo = new javax.swing.JButton();
        buttonthem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(809, 575));
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setBackground(new java.awt.Color(0, 102, 102));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nhập thông tin bệnh nhân cần thêm");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 447, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Họ và tên:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Giới tính:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Số điện thoại:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Quê quán:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("HKTT:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Ngày sinh:");

        addnam.setText("Nam");
        addnam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addnamMouseClicked(evt);
            }
        });

        addnu.setText("Nữ");
        addnu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addnuMouseClicked(evt);
            }
        });

        hovaten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hovatenActionPerformed(evt);
            }
        });

        sodienthoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sodienthoaiActionPerformed(evt);
            }
        });

        quequan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quequanActionPerformed(evt);
            }
        });

        hktt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hkttActionPerformed(evt);
            }
        });

        chonanh.setBackground(new java.awt.Color(0, 102, 102));
        chonanh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chonanh.setForeground(new java.awt.Color(255, 255, 255));
        chonanh.setText("Chọn ảnh");
        chonanh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chonanhActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        anh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        anh.setToolTipText("");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(anh, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(anh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );

        ngaysinh.setDateFormatString("dd/MM/yyyy");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ngaysinh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hovaten)))
                        .addGap(82, 82, 82))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addnam, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(addnu, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chonanh, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(hktt))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(quequan))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(sodienthoai, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chonanh)
                .addGap(57, 57, 57)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hovaten, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ngaysinh, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addnam, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addnu, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sodienthoai, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quequan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(hktt)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Mã bệnh nhân:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Mã BHYT:");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Bác sĩ khám:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("Ngày nhập viện:");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("Triệu chứng:");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("Chẩn đoán:");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("Kết luận:");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("Tình trạng nhập viện:");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setText("Ngày ra viện:");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setText("Chỉ định:");

        mabenhnhan.setEditable(false);
        mabenhnhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mabenhnhanActionPerformed(evt);
            }
        });

        mabhyt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mabhytActionPerformed(evt);
            }
        });

        bacsikham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bacsikhamActionPerformed(evt);
            }
        });

        trieuchung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trieuchungActionPerformed(evt);
            }
        });

        chandoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chandoanActionPerformed(evt);
            }
        });

        ketluan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ketluanActionPerformed(evt);
            }
        });

        chidinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chidinhActionPerformed(evt);
            }
        });

        tinhtrangnhapvien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đã xuất viện", "Đang điều trị" }));
        tinhtrangnhapvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tinhtrangnhapvienActionPerformed(evt);
            }
        });

        ngaynhapvien.setDateFormatString("dd/MM/yyyy");

        ngayxuatvien.setDateFormatString("dd/MM/yyyy");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mabenhnhan))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bacsikham))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mabhyt, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(trieuchung)
                            .addComponent(chidinh, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(chandoan)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ngayxuatvien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ngaynhapvien, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ketluan)))
                .addGap(20, 20, 20))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tinhtrangnhapvien, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mabenhnhan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(trieuchung, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bacsikham, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chandoan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chidinh, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ketluan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mabhyt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(ngaynhapvien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ngayxuatvien, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(tinhtrangnhapvien))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        buttonhuybo.setBackground(new java.awt.Color(0, 102, 102));
        buttonhuybo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonhuybo.setForeground(new java.awt.Color(255, 255, 255));
        buttonhuybo.setText("Hủy bỏ");
        buttonhuybo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonhuyboMouseClicked(evt);
            }
        });

        buttonthem.setBackground(new java.awt.Color(0, 102, 102));
        buttonthem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonthem.setForeground(new java.awt.Color(255, 255, 255));
        buttonthem.setText("Thêm");
        buttonthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonthemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonhuybo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(109, 109, 109)
                                .addComponent(buttonthem, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonthem, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonhuybo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void hovatenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hovatenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hovatenActionPerformed

    private void sodienthoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sodienthoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sodienthoaiActionPerformed

    private void quequanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quequanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quequanActionPerformed

    private void hkttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hkttActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hkttActionPerformed

    private void mabenhnhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mabenhnhanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mabenhnhanActionPerformed

    private void mabhytActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mabhytActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mabhytActionPerformed

    private void bacsikhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bacsikhamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bacsikhamActionPerformed

    private void trieuchungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trieuchungActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trieuchungActionPerformed

    private void chandoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chandoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chandoanActionPerformed

    private void ketluanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ketluanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ketluanActionPerformed

    private void chidinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chidinhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chidinhActionPerformed

    private void buttonthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonthemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonthemActionPerformed

    private void buttonhuyboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonhuyboMouseClicked
        // TODO add your handling code here:
        this.ClearBangthem();
        this.setVisible(false);
    }//GEN-LAST:event_buttonhuyboMouseClicked

    private void addnamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addnamMouseClicked
        // TODO add your handling code here:
        addnu.setSelected(false);
    }//GEN-LAST:event_addnamMouseClicked

    private void addnuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addnuMouseClicked
        // TODO add your handling code here:
        addnam.setSelected(false);
    }//GEN-LAST:event_addnuMouseClicked

    private void chonanhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chonanhActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
                chooser.showOpenDialog(null);
                File file = chooser.getSelectedFile();
                if (file != null) {
                    try {
                        // Đọc ảnh từ tệp đã chọn
                        Image image = ImageIO.read(file);
                        // Thay đổi kích thước của ảnh để lấp đầy khung JLabel
                        Image scaledImage = image.getScaledInstance(anh.getWidth(), anh.getHeight(), Image.SCALE_SMOOTH);
                        // Tạo một ImageIcon từ ảnh đã thay đổi kích thước
                        ImageIcon icon = new ImageIcon(scaledImage);
                        // Đặt icon vào JLabel để hiển thị ảnh
                        anh.setIcon(icon);
                    } catch (IOException ex) {
                        ex.printStackTrace();
                    }
                }
        
        
    }//GEN-LAST:event_chonanhActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
         this.setVisible(false);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void tinhtrangnhapvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tinhtrangnhapvienActionPerformed
        // TODO add your handling code here:
        String selectedOption = (String) tinhtrangnhapvien.getSelectedItem();
        if(selectedOption.equals("Đang điều trị")){
            ngayxuatvien.setEnabled(false);
        }
        else{
            ngayxuatvien.setEnabled(true);
        }
    }//GEN-LAST:event_tinhtrangnhapvienActionPerformed
   
    public void showMessage(String message) {
        JOptionPane.showMessageDialog(this, message);
    }
    
    public Benhnhan getBenhnhanInfo(){
        if( !validateTen()|| !validateNgaysinh() || !validateBHYT()
            || !validateSdt()|| !validateGioitinh()|| !validateQueQuan() 
                || !validateTrieuChung() || !validateChanDoan() || !validateChiDinh()
                || !validateHKTT()|| !validateBacsikham()|| !validateKetluan()
                 ||!validateNgaynhapvien() || !validateAnh() ){
            return null;
        }
        try{
        Benhnhan benhnhan = new Benhnhan();
        benhnhan.setHoTen(hovaten.getText().trim());
        benhnhan.setImageBytes(labelToByteArray(anh));
        benhnhan.setNgaySinh(ngaysinh.getDate());
        benhnhan.setNgayNhapVien(ngaynhapvien.getDate());
        benhnhan.setNgayXuatVien(ngayxuatvien.getDate());
        benhnhan.setQueQuan(quequan.getText().trim());
        benhnhan.setMaBHYT(mabhyt.getText().trim());
        if (addnam.isSelected())
             benhnhan.setGioiTinh("Nam"); 
        else if(addnu.isSelected())
             benhnhan.setGioiTinh("Nữ");
        
        String type = tinhtrangnhapvien.getSelectedItem().toString().trim();
        if (type.equals("Đã xuất viện")) {
            benhnhan.setTinhTrangXuatVien(type);
          
        } else if (type.equals("Đang điều trị")) {
            benhnhan.setTinhTrangXuatVien(type);
        }
        
        benhnhan.setSoDienThoai(sodienthoai.getText().trim());
        benhnhan.setHoKhauThuongTru(hktt.getText().trim());
        benhnhan.setTrieuChung(trieuchung.getText().trim());
        benhnhan.setChanDoan(chandoan.getText().trim());
        benhnhan.setChiDinh(chidinh.getText().trim());
        benhnhan.setBacSiKham(bacsikham.getText().trim());
        benhnhan.setKetLuan(ketluan.getText().trim());
        benhnhan.setMaBenhNhan(null);
        return benhnhan;
        } catch(Exception e){
            showMessage(e.getMessage());
        }
        return null;       
    }
    
    private boolean validateAnh() {
        Icon icon = anh.getIcon();
        if (icon == null) {
            anh.requestFocus();
            showMessage("Ảnh không được trống!");
            return false;
        }
        return true;
    }
    
    private boolean validateTen() {
        String ten = hovaten.getText();
        if (ten == null || "".equals(ten.trim())) {
            hovaten.requestFocus();
            showMessage("Tên không được trống!");
            return false;
        }
        return true;
    }

    private boolean validateNgaysinh() {
        try {
            java.util.Date today=new java.util.Date();
            Date date= ngaysinh.getDate();
            if (date.compareTo(today)==1) {
                ngaysinh.requestFocus();
                showMessage("Ngày nhập không tồn tại hoặc lớn hơn ngày hôm nay");
                return false;
            }
        } catch (Exception e) {
            ngaysinh.requestFocus();
            showMessage("Bạn đã nhập ngày sai định dạng");
            return false;
        }
        return true;
    }
    
    private boolean validateSdt() {
        String bienso = sodienthoai.getText();
        if (bienso == null || "".equals(bienso.trim()) || bienso.length() != 10) {
            sodienthoai.requestFocus();
            showMessage("Số điện thoại không được trống!");
            return false;
        }
        return true;
    }
    
    private boolean validateGioitinh() {
        if (!addnam.isSelected() && !addnu.isSelected()) {
            showMessage("Bạn chưa chọn giới tính");
            return false;
        }
        return true;
    }
    
    private boolean validateQueQuan() {
        String bienso = quequan.getText();
        if (bienso == null || "".equals(bienso.trim())) {
            quequan.requestFocus();
            showMessage("Quê quán không được trống!");
            return false;
        }
        return true;
    }
    
    private boolean validateHKTT() {
        String bienso = hktt.getText();
        if (bienso == null || "".equals(bienso.trim())) {
            hktt.requestFocus();
            showMessage("Hộ khẩu thường trú không được trống!");
            return false;
        }
        return true;
    }
    
    private boolean validateBHYT() {
        String ten = mabhyt.getText();
        if (ten == null || "".equals(ten.trim())) {
            mabhyt.requestFocus();
            showMessage("Mã bảo hiểm y tế không được trống!");
            return false;
        }
        return true;
    }
    
    private boolean validateBacsikham() {
        String bienso = bacsikham.getText();
        if (bienso == null || "".equals(bienso.trim())) {
            bacsikham.requestFocus();
            showMessage("Bác sĩ khám không được trống!");
            return false;
        }
        return true;
    }
    
    private boolean validateNgaynhapvien() {
        String type = tinhtrangnhapvien.getSelectedItem().toString().trim();
        if (type.equals("Đã xuất viện")) {
            ngayxuatvien.setEnabled(true);
            try {
            java.util.Date today = new java.util.Date();
            Date date= ngaynhapvien.getDate();
            if (date.compareTo(today) == 1) {
                ngaynhapvien.requestFocus();
                showMessage("Ngày nhập không tồn tại hoặc lớn hơn ngày hôm nay");
                return false;
            }
            
            else if(ngaysinh.getDate().compareTo(date) == 1){
                ngaynhapvien.requestFocus();
                showMessage("Ngày nhập viện không tồn tại hoặc lớn hơn ngày sinh");
                return false;
            }
            else if(ngayxuatvien != null){  
                if(date.compareTo(ngayxuatvien.getDate()) == 1){
                    ngaynhapvien.requestFocus();
                    showMessage("Ngày nhập viện không tồn tại hoặc lớn hơn ngày ra viện");
                    return false;
                }
            }
        } catch (Exception e) {
            ngaysinh.requestFocus();
            showMessage("Bạn đã nhập ngày sai định dạng");
            return false;
        }
          
        } else{
            ngayxuatvien.setEnabled(false);
            return true;
        }
        
        return true;
    }
    

    
    private boolean validateKetluan() {
        String bienso = ketluan.getText();
        if (bienso == null || "".equals(bienso.trim())) {
            ketluan.requestFocus();
            showMessage("Kết luận không được trống!");
            return false;
        }
        return true;
    }
    
    private boolean validateTrieuChung() {
        String bienso = trieuchung.getText();
        if (bienso == null || "".equals(bienso.trim())) {
            trieuchung.requestFocus();
            showMessage("Triệu chứng không được trống!");
            return false;
        }
        return true;
    }
    private boolean validateChanDoan() {
        String bienso = chandoan.getText();
        if (bienso == null || "".equals(bienso.trim())) {
            chandoan.requestFocus();
            showMessage("Chẩn đoán không được trống!");
            return false;
        }
        return true;
    }
    private boolean validateChiDinh() {
        String bienso = chidinh.getText();
        if (bienso == null || "".equals(bienso.trim())) {
            chidinh.requestFocus();
            showMessage("Chỉ định không được trống!");
            return false;
        }
        return true;
    }
    
    public void ClearBangthem() {
        this.hovaten.setText("");
        this.addnam.setSelected(false);
        this.addnu.setSelected(false);
        this.ngaysinh.setDate(null);
        this.sodienthoai.setText("");
        this.quequan.setText("");
        this.hktt.setText("");
        this.mabenhnhan.setText("");
        this.bacsikham.setText("");
        this.trieuchung.setText("");
        this.chandoan.setText("");
        this.chidinh.setText("");
        this.mabhyt.setText("");
        this.ketluan.setText("");
        this.ngaynhapvien.setDate(null);
        this.ngayxuatvien.setDate(null);
        this.ketluan.setText("");
        this.anh.setIcon(null);
    }
    private static byte[] labelToByteArray(JLabel label) {
        // Lấy biểu tượng từ JLabel
        Icon icon = label.getIcon();
        if (icon == null || !(icon instanceof ImageIcon)) {
            System.err.println("No image found in the label!");
            return null;
        }

        // Chuyển đổi biểu tượng thành hình ảnh BufferedImage
        Image image = ((ImageIcon) icon).getImage();
        BufferedImage bufferedImage = new BufferedImage(image.getWidth(null), image.getHeight(null), BufferedImage.TYPE_INT_RGB);
        Graphics2D g2d = bufferedImage.createGraphics();
        g2d.drawImage(image, 0, 0, null);
        g2d.dispose();

        // Ghi hình ảnh từ BufferedImage vào một mảng byte
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        try {
            ImageIO.write(bufferedImage, "jpg", baos);
        } catch (IOException e) {
            e.printStackTrace();
        }
        return baos.toByteArray();
    }
     public void addThemBenhnhanListener(ActionListener listener) {
        buttonthem.addActionListener(listener);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox addnam;
    private javax.swing.JCheckBox addnu;
    private javax.swing.JLabel anh;
    private javax.swing.JTextField bacsikham;
    private javax.swing.JButton buttonhuybo;
    private javax.swing.JButton buttonthem;
    private javax.swing.JTextField chandoan;
    private javax.swing.JTextField chidinh;
    private javax.swing.JButton chonanh;
    private javax.swing.JTextField hktt;
    private javax.swing.JTextField hovaten;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField ketluan;
    private javax.swing.JTextField mabenhnhan;
    private javax.swing.JTextField mabhyt;
    private com.toedter.calendar.JDateChooser ngaynhapvien;
    private com.toedter.calendar.JDateChooser ngaysinh;
    private com.toedter.calendar.JDateChooser ngayxuatvien;
    private javax.swing.JTextField quequan;
    private javax.swing.JTextField sodienthoai;
    private javax.swing.JComboBox<String> tinhtrangnhapvien;
    private javax.swing.JTextField trieuchung;
    // End of variables declaration//GEN-END:variables
}
